Refactored data persistence
Program.cs now has a database reference to the CSVDatabase. This means that we from now on use that reference to read from or write to the database.

CSVDatabase.cs implements the IDatabaseRepository.cs. It consists of a Read() and a Store() which is called within the Program.cs

FIX TO ERROR CS0579:
I had a persistent issue, which we aswell encountered 04/09 on ITU, where if we ran or built the program more than once, it would throw:
error CS0579: Duplicate global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [F:\Udvikling\CSharp\Chirp\Chirp.CLI.csproj]
F:\Udvikling\CSharp\Chirp\obj\Debug\net8.0\Chirp.CLI.AssemblyInfo.cs(13,12)
and
error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [F:\Udvikling\CSharp\Chirp\Chirp.CLI.csproj]

THIS IS NOW FIXED (right or wrong idk):
- I have set the GenerateAssemblyInfo to false in both .csproj.
- I have outcommented the Projectreference from Chirp.CLI.csproj to SimpleDB. (This does not sound right, and I think we should find a TA asap to talk about this)

Sorry for long commit description :*